name: Jaymar921 Auto Commit

on:
  schedule:
    - cron: "*/2 * * * *" # Run every 2 minutes

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Ensure full history is available

      - name: Switch to main branch
        run: git checkout main

      - name: Loop Commit Updates
        run: |
          set -e
          
          FILES=(".github/FILE.md" "README.md" ".github/FILE_2.md" ".github/FILE_3.md" ".github/FILE_4.md" ".github/FILE_5.md")  # List of files to update
          COMMIT_LOOP_COUNT=55

          echo "Configuring Git..."
          git config --global user.name "$USERNAME"
          git config --global user.email "$EMAIL"

          echo "Pulling latest changes to ensure we start with the latest commit..."
          git pull --rebase

          

          for FILE in "${FILES[@]}"; do
            echo "Checking for file: $FILE"

            for ((i=1; i<=COMMIT_LOOP_COUNT; i++)); do
              echo "Iteration $i of $COMMIT_LOOP_COUNT"
              if [ ! -f "$FILE" ]; then
                echo "File not found, creating $FILE..."
                echo "# Git Auto Commit | Hidden File" > "$FILE"
                echo "This file was added $(date +"%b %d, %Y")" >> "$FILE"
                echo "" >> "$FILE"
                echo "Just for fun and keeping my daily git commit active ðŸ¤ª" >> "$FILE"
                echo "" >> "$FILE"
                echo "commit number: 1" >> "$FILE"
              else
                echo "File exists. Updating commit number..."
                CURRENT_COUNT=$(grep -oP 'commit number: \K\d+' "$FILE" || echo "0")
                echo "Current commit number: $CURRENT_COUNT"
                NEXT_COUNT=$((CURRENT_COUNT + 1))
                sed -i "/commit number: /c\commit number: $NEXT_COUNT" "$FILE"
                echo "Updated commit number to: $NEXT_COUNT"
              fi

              echo "Contents of the file:"
              cat "$FILE"

              echo "Staging changes..."
              git add "$FILE"
              
              echo "Committing changes..."
              git commit -m "Auto commit #$NEXT_COUNT : target - ($FILE)" --allow-empty

              echo "Sleeping for 1 seconds before next commit..."
              sleep 1
            done
            
            echo "Pushing changes..."
            git push
          done

          echo "All commits completed successfully!"
        shell: bash
        env:
          USERNAME: ${{ secrets.USERNAME }}
          EMAIL: ${{ secrets.EMAIL }}
